{{- if not .Values.externalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounting-app.fullname" . }}
  labels:
    {{- include "accounting-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  GOOGLE_SA_KEY_JSON: {{ .Values.secrets.googleSaKeyJson | quote }}
{{- end }}
