{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "accounting-app.fullname" . }}
  labels:
    {{- include "accounting-app.labels" . | nindent 4 }}
  {{- if .Values.dbSetup.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: {{ include "accounting-app.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "accounting-app.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbPasswordSecretName }}
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.dbHostSecretName }}
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.dbPortSecretName }}
    - secretKey: GOOGLE_SA_KEY_JSON
      remoteRef:
        key: {{ .Values.externalSecrets.googleSaKeySecretName }}
{{- end }}
